### ISSUE TITLE
Git fat pull has poor performance when dealing with large amount of binaries

### ISSUE THREAD

**Issue by demonyangyue** [cyaninc/git-fat#43]
Hi, this issue is related with #37, while has a different scenario.

I find that when dealing with a repository which contains large amount of binaries, the performance of 
`git fat pull` becomes really bad.

We are migrating from clearcase to git these days and the git repository comes from a real cleacase vob, which is 600M and has 3420 binaries. I tested on a Ubuntu 14.04 machine with gigabytes network.

The test result of `time git fat pull` shows:

```bash
real 33m41.071s
user 21m6.557s
sys 11m13.053s
```

This is even slower than clearcase ~

Than I used cProfile and pstats to analysis the performance data, which shows the `checkout()` method is the hot spot, specifically these lines:

```python
for digest, fname in self._orphan_files():
    sub.check_call(['git', 'checkout-index', '--index', '--force', fname])
```

Per my understanding, the `checkout-index` command does three things here:

1. find the specific file in the index
2. trigger the smudge filter
3. copy the actual content of binary file

Further test shows the first step takes most of the time, I think since the index is very large and contains a lot of files, git needs some time to find out a specific file from the index. When we have lots of orphan files, the `checkout-index` command need to be executed lots of times, which makes
the performance  really bad.

I come up with a rough solution —— move the `checkout-index` line out of loop and checkout all the files from the index instead:

```python
 sub.check_call(['git', 'checkout-index', '--index', '--force', '--all'])
```
After this change, the performance improves a lot:

```bash
real 12m43.525s
user 8m12.750s
sys 4m22.912s
 ```

Will send a pull request and explain details later.
Any comments and suggestions of this issue are more than welcome.

**Comment by ajohnson23** [comment]
I'm not really a maintainer on git-fat, but speaking for myself, I think this is a really nice improvement for performance.

Some thoughts I did have:
This requires the working copy to be clean to work, right? i.e. nothing unstaged in the working directory
The old behavior didn't require that, and you could git pull on an unclean working copy with no ill effects.
This can be nice on smaller repos when you're in the middle of some changes and forgot to "git pull", so it might be nice to have a command line switch to use the old behavior. Otherwise, you'd be forced to git stash, or checkin to a branch for a second which might take more time than the --all method saves on some repos.

Hopefully I'm understanding what you've done correctly, and what I'm saying makes sense.

Also, one might argue for the old behavior to be the default with the checkout-index --all behavior requiring a switch, because some folks may have some aliases/scripts/automation they've already written that will break if git fat pull starts requiring a clean WD. I'm not sure git fat is widely deployed enough to worry about that kind of thing, but just putting it out there..

**Comment by abraithwaite** [comment]
Awesome, this could really help!  The one issue that I might see occuring is the racy git problem (which coincidently I just opened an issue on `git-lfs` for).

Basically, we have to be able to account for the case where the timestamp on the index is the same as the working copy.  We might be able to get away with calling `checkout-index` at the beginning of `checkout()` but we'd still have to check for orphans in the tree in case we have a case of the race.

See [here](https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L839-L842) for the critical lines of code.

Also @ajohnson23 brings up a good point which I didn't think about.  There may be cases where people don't want the whole index checked out, just the fat-files.  e.g. unstaged changes and switching branches is usually okay, but if we do `checkout-index --all`, I'm not sure it is okay.

**Comment by demonyangyue** [comment]
Hi all, 

Pull request 6a876f4 has been sent and thanks a lot for your comment!

Yes, `checkout-index --all` requires a clean work directory, otherwise those unstaged changes will lost. I have tried several solutions to handle this:

1.Stash the changes before `checkout-index`:

```python
sub.check_call(['git', 'stash', '--keep-index'])
sub.check_call(['git', 'checkout-index', '--index', '--force', '--all'])
sub.check_call(['git', 'stash', 'pop'])
```

But this solution may ends up with a "merge confliction" status so finally I give it up .

2.Warn user when the work directory is dirty

This is current solution in the pull request, I feel it is not elegant enough, but due to my poor understanding of git I can't come up with a better one.

@ajohnson23 ,  add a command line switch is really a great idea, since most time the old behavior works well, only when dealing with large amount of binaries the new behavior makes sense, but we still need to find a solution to handle the dirty working directory.

@abraithwaite , I didn't touch those critical lines of checking orphans, to make sure not breaking the original behavior.
 I only posted the test result of a medium-sized of a repository, when execute `git fat pull` against a large repository the old behavior would be extremely bad and hence unacceptable. So it would be awesome if we could improve the performance for these scenarios.

**Comment by ajohnson23** [comment]
<blockquote>@ajohnson23 , add a command line switch is really a great idea, since most time the old behavior works well, only when dealing with large amount of binaries the new behavior makes sense, but we still need to find a solution to handle the dirty working directory.</blockquote>
@demonyangyue Personally I'm okay with keeping the "warn the user and exit" behavior for now, especially if the new behavior only happens when a command line switch is passed to git fat pull. Cleaning a working copy is something the user should probably handle their own way on their own terms.

If you're feeling like experimenting more, you could do something like (excuse the C-like pseudocode, I'm not a python scripter):
```
if( there are staged files ) {
        git commit -m "staged files"
}
if( there are unstaged files ) {
        git add -A
        git commit -m "unstaged files"
}
git checkout-index ...
if( there were staged files ) {
        git checkout --soft HEAD^
}
if( there were unstaged files ) {
        git checkout --mixed HEAD^
}
```
This is totally off the cuff, and I have no idea if it's a good idea, and it may not handle edge cases (or even non-edge cases) :)

**Comment by demonyangyue** [comment]
Hi @ajohnson23 ,

Your suggestion about combining `git commit` and `git reset` to simulate stash looks really great, but I have some concerns about the corner case:
* What if the program is in `git checkout-index...` line, and the user press "CTRL + C"
* As you mentioned, the usre may want to handle their own way on the unstaged files, may not always `git add -A`,  for example  a user have done a lot of changes but want to abandon them before `git fat pull` :)

I totally agree with you that combine "warn the user and exit" with a command line switch should be better, I will revise the pull request if @abraithwaite also thinks this is the most suitable solution.

**Comment by ajohnson23** [comment]
With git commit in this way nothing is truly ever lost -- it can be examined with "git reflog" and restored. And they can still abandon all of those unstaged changes/files even after the git fat pull (they'll still be unstaged).
The downside is, they'll also be in the local repository as an unreferenced commit :/ That won't go away until the next prune. So maybe that's what you're referring to. And good point on the Ctrl+C problem... you basically need to do everything in a transactional way to be safe, and while it's true they can restore things by looking at reflog later, it's a lot to expect of the user...

Anywho, I do think the git fat pull commandline switch + warn/exit is the best approach as you mentioned.

Thanks for noticing this little inefficiency, I think it will really help with pull performance. Even if it doesn't go into this repo I'll be patching my local copy :)

**Comment by ajohnson23** [comment]
Btw, a really great use of this flag will be on automated build runners (continuous integration type stuff) where you never have an unclean working copy in the first place.
