### ISSUE TITLE
Git Fat running out of memory on file just under 2gb

### ISSUE THREAD

**Issue by wduncanfraser** [cyaninc/git-fat#51]
Version: 0.4.0
Platform: Windows 7 x86_64
Git Version: 1.9.5.msysgit.1
Python: 2.7.9

In one of my repositories I have a large .7z file which is about 2gb in size. On a git add, with git fat initialized, I immediately get a "fatal: Out of memory, realloc failed". If I remove just that file, git add works without a hitch. Similar repositories with .7z files up to 1.2gb in size are able to add without issue.

Just as a test, I moved the file into a repository without git fat initialized, and it was able to add normally.

**Comment by justinclift** [comment]
Out of curiosity, how much ram is in the system this happens on?

**Comment by wduncanfraser** [comment]
I have 32gb of ram installed on this system. Usage is currently floating around 7gb. When initiating a git add, usage barely spikes .1gb before it fails.

**Comment by justinclift** [comment]
Cool.  So it's definitely not a problem with git doing something dumb like making 2 copies of the file in ram on a 4gb ram system. (was just curious) :smile:

**Comment by justinclift** [comment]
@CzarekTomczak Any ideas on this?

**Comment by abraithwaite** [comment]
Sorry I'm not more familar with windows but is it possible to get a stacktrace of what happened?  It sounds like it happened in the filter clean, but I'm not familiar with windows enough to begin to guess what happened. [Here's](https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L652-L673) the relevent section of code.

Additionally, I'm not sure how the `hasher.update` function works.  (It's sha1 so streams should be fine)

https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L240-L253

**Comment by cztomczak** [comment]
Were there any other important messages in the console?

The error message "fatal: Out of memory, realloc failed" looks to be generated by git (googled it). However the issue seems to be caused by the usage of the git fat filter.

@justinclift I assume that both python and msysgit are 32bit binaries, so the memory limit is 2GB even if he has 32GB of ram. See http://stackoverflow.com/questions/639540/how-much-memory-can-a-32-bit-process-access-on-a-64-bit-operating-system

**Comment by AndrewJDR** [comment]
I believe there are 64-bit python binaries available for windows, so you you haven't tried that yet, you can.

As for msysgit, I don't think that is 64-bit yet. One idea would be to try the 64-bit git included with cygwin on windows.

**Comment by justinclift** [comment]
@CzarekTomczak Ahhhh ok.  With [DB4S](https://github.com/sqlitebrowser/sqlitebrowser), we only recently added a 64-bit Windows build (using Visual Studio Community edition) so we can work with larger databases.

I'd kind of assumed Git would have been through that process already. :wink:

**Comment by cztomczak** [comment]
The git fat wheel package for Windows is available only for 32bit on PyPI, so it can only be installed on Python 32bit I think. The 64bit package binaries can still contain 32bit exe/dll binaries for the external tools (ssh, rsync, gawk), so there aren't any changes required, only a separate package needs to be generated using Python 64bit. Let me know if anyone needs such and I can create 64bit package and send it to Alan. From what I know most people use Python 32bit on 64bit Windows. But still the issue is that msysgit is available only as 32bit binaries.

**Comment by wduncanfraser** [comment]
Did a little testing this weekend at home. I'll be verifying at the office Monday but it looks like I have a solution. I can confirm that git-fat currently only works with 32bit on PyPI. However, installing a 64bit version of git from http://git-for-windows.github.io/ (Which looks like it is a full replacement of msysgit) fixed the issue. Was able to git add a couple files larger than 2gb in testing. So it looks like as long as git is running 64bit, the python dependency can still be at 32bit in order to support large memory addressing.

**Comment by justinclift** [comment]
Sounds like the 64-bit version of git fat wheel package would be useful on PyPi after all.

**Comment by wduncanfraser** [comment]
Whoops, forgot to reply back earlier that I confirmed 64bit git working on the files in question.
